import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProviders from "@/providers/query-provider";
import {ClerkProvider} from "@clerk/nextjs"
import {SidebarInset, SidebarProvider,SidebarTrigger } from "@/components/ui/sidebar";
import { Providers } from "@/providers/LbProvider";
import { AppSidebar } from "@/components/app-sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{cssLayerName:'clerk'}}
    >
       <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          
        <QueryProviders>
          <Providers>
         
          <div className="flex flex-col fixed inset-0 overflow-hidden">
            
           {children}
          </div>
          
        
        </Providers>
        </QueryProviders>
        
        </SidebarProvider>
        
       
       
      </body>
    </html>
    </ClerkProvider>
   
  );
}
